Enigme 3 : secret exit
Natacha-ds/escapegame pull request #15
Opened 2020-05-27 15:56 UTC by Natacha-ds

- Création de l'énigme : chemin caché vers une croix qui mène à la prochaine énigme >> je pense qu'on peut raccourcir encore le code en créant un autre component pour chaque ligne de block plutôt que le répéter partout mais je ne vois pas ensuite comment attribuer à la bonne ligne la bonne lettre (props forever)
- Redirection faite sur HP car la prochaine enigme n'est pas commencée
- Ajout de la redirection de l'énigme 2 vers celle ci.

2020-05-27 16:35 UTC, Taskim requested changes

2020-05-27 16:35 UTC, Taskim commented on src/App.js
>                  {/* A <Switch> looks through its children <Route>s and
hésite pas à virer ce commentaire quand tu veux :)

2020-05-27 16:35 UTC, Taskim commented on src/components/ColorsAndLetters/index.js
> +    function handleRedirection() {
tu sais que tu as une autre possibilité, utiliser les composants Link de react router

2020-05-27 16:35 UTC, Taskim commented on src/components/SecretExit/index.js
> +                <ExitBlock text={bottomArrow()} />
à quoi ça sert tous ces exitblock ? 🤔 j'pense que ton code est trop complexe pour ce qu'il doit faire

2020-05-28 12:03 UTC, Natacha-ds commented on src/App.js
>                  {/* A <Switch> looks through its children <Route>s and
done

2020-05-28 14:00 UTC, Natacha-ds commented on src/components/ColorsAndLetters/index.js
> +    function handleRedirection() {
Ok j'ai changé pour celui là ! 
Par contre si le lien est dans un autre composant, comme je peux faire avec Link ?

2020-05-28 14:00 UTC, Natacha-ds commented on src/components/SecretExit/index.js
> +                <ExitBlock text={bottomArrow()} />
Ok j'ai tout revu, c'est dans le next pull request

2020-05-28 16:17 UTC, Taskim approved these changes

2020-05-30 14:56 UTC, merged