ajout barre de progression
Natacha-ds/escapegame pull request #19
Opened 2020-06-10 13:54 UTC by Natacha-ds

- ajout d'une barre de progression
- suppression de l'ancien menu

2020-06-10 21:14 UTC, Taskim requested changes

2020-06-10 21:14 UTC, Taskim commented on src/App.css
>  }
tu es sûre d'utiliser tout ce css ? 👀

2020-06-10 21:14 UTC, Taskim commented on src/App.js
> +    useLocation,
Tu devrais dans une autre PR regarder comment installer et configurer ESLint, qui fonctionne aussi dans VSCode. Ça te permettrait de voir direct que tu n'utilises pas ça, et que tu l'as importé inutilement.
Sinon tu l'as dans le terminal et dans le navigateur
![image](https://user-images.githubusercontent.com/14927805/84319026-a10e2600-ab6f-11ea-84dd-0cbbb3bcc527.png)

2020-06-10 21:14 UTC, Taskim commented on src/components/Home/index.js
> +                {' '}
![bitmoji](https://render.bitstrips.com/v2/cpanel/822076c9-6743-49b9-8de3-3fbce68f5f20-1731a188-ea16-49c3-83c0-aa3f8979e7dd-v1.png?transparent=1&palette=1&width=246)

2020-06-10 21:14 UTC, Taskim commented on src/components/ProgressBar/index.js
> +            );
![bitmoji](https://sdk.bitmoji.com/render/panel/fbf70eb2-c012-465e-9c1e-7b092675dfd8-1731a188-ea16-49c3-83c0-aa3f8979e7dd-v1.png?transparent=1&palette=1&width=246)

Et tu t'es dit que j'allais valider ça normal ? 😆

2020-06-11 10:05 UTC, Natacha-ds commented on src/App.css
>  }
non il était là de base je n'y ai pas vraiment fais gaffe

2020-06-11 10:07 UTC, Natacha-ds commented on src/App.js
> +    useLocation,
je el vois déjà dans vs code c'est en clair c'est juste que je fais pas toujours attention

2020-06-11 10:07 UTC, Natacha-ds commented on src/components/Home/index.js
> +                {' '}
pas compris ton retour ?

2020-06-11 13:33 UTC, Natacha-ds commented on src/components/ProgressBar/index.js
> +            );
Si tu pouvais m'en dire plus parce qu'a part que c'est mal fait je ne sais pas ce qui ne va pas vu que ca marche

2020-06-24 11:01 UTC, merged